---
- name: Deploy of the Auto Tagging Machine
  hosts: localhost
  gather_facts: false
  vars:
    aws_access_key: <ACCESS_KEY>
    aws_secret_key: <SECRET_KEY>
    role_name: Role_Auto_Tagging_Machine

  tasks:

  - name: Create a role for the Lambda function (authorize tagging)
    iam_role:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: "{{ role_name }}"
      state: present
      assume_role_policy_document: "{{ lookup('file', 'iam_policy.json') }}"
      description: Role create by Ansible
    register: role

  - name : Add Policies to the Role
    iam_policy:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      iam_name: "{{ role_name }}"
      iam_type: role
      policy_name: AuthorizeTaggingAndLogging
      state: present
      policy_json: "{{ lookup('file', 'iam_role.json') }}"

  - name: Create the lambda function
    lambda:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: ATM_machine
      region: "eu-west-1"
      state: present
      zip_file: "code.zip"
      runtime: "python3.6"
      memory_size: 128
      timeout: 60
      role: "{{ role.arn }}"
      handler: "handler.auto_tagging"
    register: function

  - name: Create the CloudWatch Rule
    cloudwatchevent_rule:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "eu-west-1"
      name: EventsForATM
      event_pattern: "{{ lookup('file', 'cloudwatch_event.json') }}"
      description: Run my scheduled task
      targets:
        - id: MyTargetId
          arn: "{{ function.configuration.function_arn }}"
