AWSTemplateFormatVersion: "2010-09-09"
Description: "Deployment of the tagging machine"

Parameters:
  BucketName:
    Type: String
    Description: "Name of the S3 Bucket where the code archive has been uploaded"
  CodeFileName:
    Type: String
    Description: "Name of the ZIP file"


Resources:

  AutoTaggingMachine:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: arn:aws:logs:*:*:*
              - Action: tag:TagResources
                Effect: Allow
                Resource: '*'
              - Action: ec2:CreateTags
                Effect: Allow
                Resource: '*'
              - Action: dynamodb:TagResource
                Effect: Allow
                Resource: '*'
              - Action:
                  - s3:PutBucketTagging
                  - s3:GetBucketTagging
                Effect: Allow
                Resource: '*'
              - Action: sqs:TagQueue
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: AllowTaggingAndLogging



  AutoTaggingMachineFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref CodeFileName
      Handler: handler.auto_tagging
      Role: !GetAtt 'AutoTaggingMachine.Arn'
      Runtime: python3.6
      Timeout: 60



  AutoTaggingMachineRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule for tagging AWS resources
      EventPattern:
        detail:
          eventName:
            - RunInstances
            - CreateBucket
            - CreateImage
            - CreateDhcpOptions
            - CreateNetworkAcl
            - CreateNetworkInterface
            - CreateQueue
            - CreateRouteTable
            - CreateSecurityGroup
            - CreateSnapshot
            - CreateSubnet
            - CreateTable
            - CreateVolume
            - CreateVpc
            - CreateInternetGateway
          eventSource:
            - ec2.amazonaws.com
            - dynamodb.amazonaws.com
            - s3.amazonaws.com
            - sqs.amazonaws.com
        detail-type:
          - AWS API Call via CloudTrail
        source:
          - aws.ec2
          - aws.dynamodb
          - aws.s3
          - aws.sqs
      State: ENABLED
      Targets:
        - Arn: !GetAtt 'AutoTaggingMachineFunction.Arn'
          Id: AutoTaggingMachineRule



  AutoTaggingMachineInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt 'AutoTaggingMachineFunction.Arn'
      Principal: events.amazonaws.com
      SourceArn: !GetAtt 'AutoTaggingMachineRule.Arn'
